// <auto-generated />
using System;
using FapPiloto.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FapPiloto.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326203849_ExpandDniMockRecords")]
    partial class ExpandDniMockRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("FapPiloto.Api.Entities.ApplicantRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MilitaryServiceInterest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.DniMockRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("DniMockRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2008, 3, 15),
                            Dni = "70000001",
                            FirstNames = "Carlos Alberto",
                            Gender = "M",
                            MaternalSurname = "Huamán",
                            PaternalSurname = "Quispe"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2008, 7, 22),
                            Dni = "70000002",
                            FirstNames = "Luis Fernando",
                            Gender = "M",
                            MaternalSurname = "Condori",
                            PaternalSurname = "Mamani"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2008, 1, 10),
                            Dni = "70000003",
                            FirstNames = "Ana María",
                            Gender = "F",
                            MaternalSurname = "Ramos",
                            PaternalSurname = "Flores"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(2008, 11, 5),
                            Dni = "70000004",
                            FirstNames = "Diego Alejandro",
                            Gender = "M",
                            MaternalSurname = "Silva",
                            PaternalSurname = "Torres"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(2008, 5, 18),
                            Dni = "70000005",
                            FirstNames = "Rosa María",
                            Gender = "F",
                            MaternalSurname = "Mendoza",
                            PaternalSurname = "García"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(2008, 9, 30),
                            Dni = "70000006",
                            FirstNames = "Pedro José",
                            Gender = "M",
                            MaternalSurname = "Chávez",
                            PaternalSurname = "Rojas"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(2008, 2, 14),
                            Dni = "70000007",
                            FirstNames = "María Elena",
                            Gender = "F",
                            MaternalSurname = "Paredes",
                            PaternalSurname = "Vargas"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(2008, 8, 25),
                            Dni = "70000008",
                            FirstNames = "Jorge Luis",
                            Gender = "M",
                            MaternalSurname = "Herrera",
                            PaternalSurname = "Castillo"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(2008, 12, 1),
                            Dni = "70000009",
                            FirstNames = "Lucía Fernanda",
                            Gender = "F",
                            MaternalSurname = "Ruiz",
                            PaternalSurname = "Salazar"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(2008, 4, 8),
                            Dni = "70000010",
                            FirstNames = "Miguel Ángel",
                            Gender = "M",
                            MaternalSurname = "Díaz",
                            PaternalSurname = "Espinoza"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(2008, 5, 12),
                            Dni = "70000011",
                            FirstNames = "Sonia Patricia",
                            Gender = "F",
                            MaternalSurname = "Soto",
                            PaternalSurname = "Palomino"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(2008, 1, 25),
                            Dni = "70000012",
                            FirstNames = "Roberto Carlos",
                            Gender = "M",
                            MaternalSurname = "Rivas",
                            PaternalSurname = "Delgado"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(2008, 10, 3),
                            Dni = "70000013",
                            FirstNames = "Andrea Cecilia",
                            Gender = "F",
                            MaternalSurname = "Silva",
                            PaternalSurname = "Navarro"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateOnly(2008, 6, 30),
                            Dni = "70000014",
                            FirstNames = "Andrés Avelino",
                            Gender = "M",
                            MaternalSurname = "Dongo",
                            PaternalSurname = "Cáceres"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateOnly(2008, 2, 8),
                            Dni = "70000015",
                            FirstNames = "Gabriela Pilar",
                            Gender = "F",
                            MaternalSurname = "Bravo",
                            PaternalSurname = "Medina"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateOnly(2008, 11, 15),
                            Dni = "70000016",
                            FirstNames = "Francisco Javier",
                            Gender = "M",
                            MaternalSurname = "Guzmán",
                            PaternalSurname = "Pardo"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateOnly(2008, 8, 19),
                            Dni = "70000017",
                            FirstNames = "Beatriz Clara",
                            Gender = "F",
                            MaternalSurname = "León",
                            PaternalSurname = "Montalvo"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateOnly(2008, 3, 22),
                            Dni = "70000018",
                            FirstNames = "Víctor Manuel",
                            Gender = "M",
                            MaternalSurname = "Uribe",
                            PaternalSurname = "Salazar"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateOnly(2008, 7, 14),
                            Dni = "70000019",
                            FirstNames = "Isabel Cristina",
                            Gender = "F",
                            MaternalSurname = "Ortiz",
                            PaternalSurname = "Bustamante"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateOnly(2008, 1, 1),
                            Dni = "70000020",
                            FirstNames = "Álvaro José",
                            Gender = "M",
                            MaternalSurname = "Roca",
                            PaternalSurname = "Cornejo"
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateOnly(2008, 4, 11),
                            Dni = "70000021",
                            FirstNames = "Daniela Roxana",
                            Gender = "F",
                            MaternalSurname = "Vega",
                            PaternalSurname = "Villanueva"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateOnly(2008, 2, 28),
                            Dni = "70000022",
                            FirstNames = "Héctor Ricardo",
                            Gender = "M",
                            MaternalSurname = "Lapa",
                            PaternalSurname = "Guerrero"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateOnly(2008, 9, 7),
                            Dni = "70000023",
                            FirstNames = "Carmen Julia",
                            Gender = "F",
                            MaternalSurname = "Saavedra",
                            PaternalSurname = "Mendoza"
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateOnly(2008, 6, 17),
                            Dni = "70000024",
                            FirstNames = "Eduardo Felipe",
                            Gender = "M",
                            MaternalSurname = "Luna",
                            PaternalSurname = "Ibañez"
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateOnly(2008, 12, 5),
                            Dni = "70000025",
                            FirstNames = "Natalia Emperatriz",
                            Gender = "F",
                            MaternalSurname = "Paz",
                            PaternalSurname = "Arias"
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateOnly(2008, 11, 20),
                            Dni = "70000026",
                            FirstNames = "Oscar Enrique",
                            Gender = "M",
                            MaternalSurname = "Salcedo",
                            PaternalSurname = "Balbi"
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateOnly(2008, 10, 31),
                            Dni = "70000027",
                            FirstNames = "Silvia Irene",
                            Gender = "F",
                            MaternalSurname = "Ríos",
                            PaternalSurname = "Carvajal"
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateOnly(2008, 5, 25),
                            Dni = "70000028",
                            FirstNames = "Manuel Antonio",
                            Gender = "M",
                            MaternalSurname = "Moreno",
                            PaternalSurname = "Belgrano"
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateOnly(2008, 3, 8),
                            Dni = "70000029",
                            FirstNames = "Claudia Cecilia",
                            Gender = "F",
                            MaternalSurname = "Lazo",
                            PaternalSurname = "Zegarra"
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateOnly(2008, 7, 2),
                            Dni = "70000030",
                            FirstNames = "Rafael Humberto",
                            Gender = "M",
                            MaternalSurname = "Cisneros",
                            PaternalSurname = "Ferrand"
                        },
                        new
                        {
                            Id = 31,
                            BirthDate = new DateOnly(2008, 9, 13),
                            Dni = "70000031",
                            FirstNames = "Marita Elena",
                            Gender = "F",
                            MaternalSurname = "Dávila",
                            PaternalSurname = "Aranda"
                        },
                        new
                        {
                            Id = 32,
                            BirthDate = new DateOnly(2008, 1, 15),
                            Dni = "70000032",
                            FirstNames = "Julio César",
                            Gender = "M",
                            MaternalSurname = "Brizuela",
                            PaternalSurname = "Santisteban"
                        },
                        new
                        {
                            Id = 33,
                            BirthDate = new DateOnly(2008, 4, 30),
                            Dni = "70000033",
                            FirstNames = "Verónica Lucía",
                            Gender = "F",
                            MaternalSurname = "Lynch",
                            PaternalSurname = "Peralta"
                        },
                        new
                        {
                            Id = 34,
                            BirthDate = new DateOnly(2008, 6, 21),
                            Dni = "70000034",
                            FirstNames = "Guillermo León",
                            Gender = "M",
                            MaternalSurname = "Carranza",
                            PaternalSurname = "Aliaga"
                        },
                        new
                        {
                            Id = 35,
                            BirthDate = new DateOnly(2008, 8, 1),
                            Dni = "70000035",
                            FirstNames = "Diana Carolina",
                            Gender = "F",
                            MaternalSurname = "Ramos",
                            PaternalSurname = "Chirinos"
                        },
                        new
                        {
                            Id = 36,
                            BirthDate = new DateOnly(2008, 11, 11),
                            Dni = "70000036",
                            FirstNames = "Fernando Alfonso",
                            Gender = "M",
                            MaternalSurname = "Tirado",
                            PaternalSurname = "Reaño"
                        },
                        new
                        {
                            Id = 37,
                            BirthDate = new DateOnly(2008, 2, 19),
                            Dni = "70000037",
                            FirstNames = "Karen Vanessa",
                            Gender = "F",
                            MaternalSurname = "Echegaray",
                            PaternalSurname = "Gallardo"
                        },
                        new
                        {
                            Id = 38,
                            BirthDate = new DateOnly(2008, 5, 2),
                            Dni = "70000038",
                            FirstNames = "Pablo Francisco",
                            Gender = "M",
                            MaternalSurname = "Olaya",
                            PaternalSurname = "Zárate"
                        },
                        new
                        {
                            Id = 39,
                            BirthDate = new DateOnly(2008, 10, 18),
                            Dni = "70000039",
                            FirstNames = "Milagros Rosario",
                            Gender = "F",
                            MaternalSurname = "Paz",
                            PaternalSurname = "Quimper"
                        },
                        new
                        {
                            Id = 40,
                            BirthDate = new DateOnly(2008, 7, 7),
                            Dni = "70000040",
                            FirstNames = "Alejandro Román",
                            Gender = "M",
                            MaternalSurname = "Palacios",
                            PaternalSurname = "Ugarte"
                        },
                        new
                        {
                            Id = 41,
                            BirthDate = new DateOnly(2008, 1, 12),
                            Dni = "70000041",
                            FirstNames = "Gisella Ivonne",
                            Gender = "F",
                            MaternalSurname = "Letts",
                            PaternalSurname = "Osterling"
                        },
                        new
                        {
                            Id = 42,
                            BirthDate = new DateOnly(2008, 3, 29),
                            Dni = "70000042",
                            FirstNames = "Pedro Abelardo",
                            Gender = "M",
                            MaternalSurname = "Llanos",
                            PaternalSurname = "Guevara"
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateOnly(2008, 12, 9),
                            Dni = "70000043",
                            FirstNames = "Tania Libertad",
                            Gender = "F",
                            MaternalSurname = "Casas",
                            PaternalSurname = "Noriega"
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateOnly(2008, 6, 2),
                            Dni = "70000044",
                            FirstNames = "Marco Antonio",
                            Gender = "M",
                            MaternalSurname = "Reynoso",
                            PaternalSurname = "Solis"
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateOnly(2008, 8, 21),
                            Dni = "70000045",
                            FirstNames = "Elena Sofía",
                            Gender = "F",
                            MaternalSurname = "Arizmendi",
                            PaternalSurname = "Mendiola"
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateOnly(2008, 5, 14),
                            Dni = "70000046",
                            FirstNames = "José Carlos",
                            Gender = "M",
                            MaternalSurname = "Lira",
                            PaternalSurname = "Mariátegui"
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateOnly(2008, 9, 2),
                            Dni = "70000047",
                            FirstNames = "Rosa Luz",
                            Gender = "F",
                            MaternalSurname = "Alvarado",
                            PaternalSurname = "Velasco"
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateOnly(2008, 7, 10),
                            Dni = "70000048",
                            FirstNames = "Emilio Martín",
                            Gender = "M",
                            MaternalSurname = "Westphalen",
                            PaternalSurname = "Adolfo"
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateOnly(2008, 1, 20),
                            Dni = "70000049",
                            FirstNames = "Blanca Varela",
                            Gender = "F",
                            MaternalSurname = "Prada",
                            PaternalSurname = "Gonzáles"
                        },
                        new
                        {
                            Id = 50,
                            BirthDate = new DateOnly(2008, 8, 30),
                            Dni = "70000050",
                            FirstNames = "Abraham Valdelomar",
                            Gender = "M",
                            MaternalSurname = "Arias",
                            PaternalSurname = "Pinto"
                        });
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Registro y consulta de inscripciones",
                            Name = "Operador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dashboard, auditoría y administración",
                            Name = "Supervisor"
                        });
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Juan Perez Garcia",
                            IsActive = true,
                            PasswordHash = "$2a$11$NhepLipSKikTxA2fidUxgusxwg6vMNwna7kiXYSREk.7v3kfG9Z.q",
                            RoleId = 1,
                            Username = "operador1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Maria Lopez Torres",
                            IsActive = true,
                            PasswordHash = "$2a$11$QE.J0.pwT4X6/pbDUSXQ4.I1rXaC3JcmG7L0yxL/Y32k7jXWNl0Du",
                            RoleId = 2,
                            Username = "supervisor1"
                        });
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.ApplicantRegistration", b =>
                {
                    b.HasOne("FapPiloto.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FapPiloto.Api.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("FapPiloto.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.User", b =>
                {
                    b.HasOne("FapPiloto.Api.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
