// <auto-generated />
using System;
using FapPiloto.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FapPiloto.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324202901_AddBiometricsAndDualFlow")]
    partial class AddBiometricsAndDualFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("FapPiloto.Api.Entities.ApplicantRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MilitaryServiceInterest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.DniMockRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaternalSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("DniMockRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2008, 3, 15),
                            Dni = "70000001",
                            FirstNames = "Carlos Alberto",
                            Gender = "M",
                            MaternalSurname = "Huamán",
                            PaternalSurname = "Quispe"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2008, 7, 22),
                            Dni = "70000002",
                            FirstNames = "Luis Fernando",
                            Gender = "M",
                            MaternalSurname = "Condori",
                            PaternalSurname = "Mamani"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2008, 1, 10),
                            Dni = "70000003",
                            FirstNames = "Ana María",
                            Gender = "F",
                            MaternalSurname = "Ramos",
                            PaternalSurname = "Flores"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(2008, 11, 5),
                            Dni = "70000004",
                            FirstNames = "Diego Alejandro",
                            Gender = "M",
                            MaternalSurname = "Silva",
                            PaternalSurname = "Torres"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(2008, 5, 18),
                            Dni = "70000005",
                            FirstNames = "Rosa María",
                            Gender = "F",
                            MaternalSurname = "Mendoza",
                            PaternalSurname = "García"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(2008, 9, 30),
                            Dni = "70000006",
                            FirstNames = "Pedro José",
                            Gender = "M",
                            MaternalSurname = "Chávez",
                            PaternalSurname = "Rojas"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(2008, 2, 14),
                            Dni = "70000007",
                            FirstNames = "María Elena",
                            Gender = "F",
                            MaternalSurname = "Paredes",
                            PaternalSurname = "Vargas"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(2008, 8, 25),
                            Dni = "70000008",
                            FirstNames = "Jorge Luis",
                            Gender = "M",
                            MaternalSurname = "Herrera",
                            PaternalSurname = "Castillo"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(2008, 12, 1),
                            Dni = "70000009",
                            FirstNames = "Lucía Fernanda",
                            Gender = "F",
                            MaternalSurname = "Ruiz",
                            PaternalSurname = "Salazar"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(2008, 4, 8),
                            Dni = "70000010",
                            FirstNames = "Miguel Ángel",
                            Gender = "M",
                            MaternalSurname = "Díaz",
                            PaternalSurname = "Espinoza"
                        });
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Registro y consulta de inscripciones",
                            Name = "Operador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dashboard, auditoría y administración",
                            Name = "Supervisor"
                        });
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Juan Pérez García",
                            IsActive = true,
                            PasswordHash = "$2a$11$2R8VTm.p9tI7hwVZN3yN6uARRWCq6LKWVhJxvZgzxlSpI2P9uxqZ2",
                            RoleId = 1,
                            Username = "operador1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "María López Torres",
                            IsActive = true,
                            PasswordHash = "$2a$11$Ewo4REX20txlBaNwoKLslOyUIDIQVi.G/OjeHz.XAM6D/VbdNOsHC",
                            RoleId = 2,
                            Username = "supervisor1"
                        });
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.ApplicantRegistration", b =>
                {
                    b.HasOne("FapPiloto.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FapPiloto.Api.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("FapPiloto.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.User", b =>
                {
                    b.HasOne("FapPiloto.Api.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FapPiloto.Api.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
